config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static#home'
  get '/about', to: 'static#about', as: :about

	resources :hookahs do
		member do
			post 'upvote'
			post 'downvote'
		end
	end

end

app/models/hookah.rb
class Hookah < ActiveRecord::Base
	has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :hookah
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hookahs_controller.rb
class HookahsController < ApplicationController
  before_action :set_hookah, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /hookahs
  # GET /hookahs.json
  def index
    @hookahs = Hookah.order(votes: :desc)
  end

  def show
  	@review = @hookah.reviews.build
  end

  # GET /hookahs/new
  def new
    @hookah = Hookah.new
  end

  # GET /hookahs/1/edit
  def edit
  end

  def create
    @hookah = Hookah.new(hookah_params)

    respond_to do |format|
    	if @hookah.save
    		format.html { redirect_to hookahs_path, notice: 'Hookah was successfully created.'}
    		format.json { render :show, status: :created, location: @hookah }
    	else
    		format.html { render :new }
    		format.json { render json: @hookah.errors, status: :unprocessable_entity }
    	end
    end
  end

  def update
  	if @hookah.update_attributes(hookah_params)
  		redirect_to root_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@hookah.destroy
  	redirect_to root_path
  end

  def upvote
  	@hookah = Hookah.find(params[:id])
  	@hookah.votes.create
  	redirect_to(hookahs_path)
  end

  def downvote
  	@hookah = Hookah.find(params[:id])
  	@hookah.votes -= 1
  	@hookah.save
  	redirect_to(hookahs_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hookah
      @hookah = Hookah.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hookah_params
      params.require(:hookah).permit(:title, :description)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hookahs_helper.rb
module HookahsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/hookahs/_form.html.erb
<%= form_for(@hookah) do |f| %>
  <% if @hookah.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hookah.errors.count, "error") %> prohibited this hookah from being saved:</h2>

      <ul>
      <% @hookah.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hookahs/edit.html.erb
<h1>Editing Hookah</h1>

<%= render 'form' %>

<%= link_to 'Show', @hookah %> 
<%= link_to 'Back', hookahs_path %>

app/views/hookahs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hookah Creations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @hookahs.each do |hookah| %>
    	<tr>
    		<td><%= hookah.title %></td>
    		<td><%= hookah.description %></td>
    		<td><%= pluralize(hookah.votes.count, "vote") %></td>
        <td><%= button_to '+1', upvote_hookah_path(hookah), method: :post %></td>
        <td><%= link_to 'Delete', hookah, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hookah', new_hookah_path %>

app/views/hookahs/new.html.erb
<h1>New Hookah</h1>

<%= render 'form' %>

<%= link_to 'Back', hookahs_path %>

app/views/hookahs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @hookah.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hookah.description %>
</p>

<%= link_to 'Edit', edit_hookah_path(@hookah) %> |
<%= link_to 'Back', hookahs_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Hookahs', hookahs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HookahApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>